FAMILY_SPECS = {
    "Athletics": {
        "prompts": [
            "basketball court soccer field or running track",
            "gym workout or exercise session",
            "rock climbing wall or hiking trail",
            "athletes playing sports or working out",
            "sports competition with physical motion",
            "exercise or fitness training scene",
            "team or solo athletic activity",
        ],
        "detector_weights": {
            "sports ball": 8.0,
            "bicycle": 7.0,
            "surfboard": 7.0,
            "skateboard": 7.0,
            "tennis racket": 6.0,
            "frisbee": 6.0,
            "baseball bat": 7.0,
            "baseball glove": 7.0,
            "skis": 7.0,
            "snowboard": 7.0,
            "kite": 0.5,
        },
        "modules": ["athletics_family"],
    },
    "Smarts": {
        "prompts": [
            "student studying with books and notes",
            "school work with laptop and books on desk",
            "homework or exam preparation with books",
            "academic research papers and laptop on a desk",
            "coding or focused desk work with computer",
            "library or classroom study scene",
            "chess board strategy game on a table",
        ],
        "detector_weights": {
            "laptop": 6.0,
            "book": 3.5,
            "backpack": 1.0,
        },
        "modules": ["smarts_family"],
    },
    "Sociability": {
        "prompts": [
            "friends or family social gathering",
            "people eating celebrating or hanging out together",
            "supportive or helping interaction between people",
            "group social scene with tables drinks or cake",
            "friends shopping or hanging out",
            "family group moment",
            "social celebration or hangout",
        ],
        "detector_weights": {
            "dining table": 3.0,
            "cake": 3.0,
            "cup": 1.0,
            "chair": 0.7,
            "bench": 0.6,
        },
        "modules": ["social_family"],
    },
    "Vibes": {
        "prompts": [
            "city skyline or landmark sightseeing photo",
            "mountain landscape or scenic nature view",
            "tourist at a city landmark or tower",
            "outdoor scenic viewpoint or skyline",
            "nature or travel scenery photo",
            "vacation or sightseeing destination scene",
            "scenic landscape or landmark moment",
        ],
        "detector_weights": {
            "dog": 3.5,
            "cat": 3.5,
            "car": 0.8,
            "bus": 0.8,
            "train": 0.8,
            "airplane": 1.4,
            "boat": 1.2,
        },
        "modules": ["vibes_family"],
    },
    "Creativity": {
        "prompts": [
            "pencil sketch or drawing on paper",
            "paintbrush painting on canvas or easel",
            "music studio with microphone or instrument",
            "artist at work with sketchbook canvas or instrument",
            "art supplies sketchbook or easel scene",
            "recording studio or music practice",
            "photographer visibly holding camera up to take a shot",
        ],
        "detector_weights": {
            "cell phone": 0.6,
        },
        "modules": ["creativity_family"],
    },
}